// Generated by CoffeeScript 1.12.2
(function() {
  var express, router;

  express = require('express');

  router = express.Router();

  router.get('/', function(req, res, next) {
    var fs, md;
    fs = require('fs');
    md = fs.readFileSync('doc/start.md', 'utf-8');
    return res.send(md);
  });

  module.exports = router;

}).call(this);
